language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install sdrfcheck

script:
  - git diff-tree --no-commit-id --name-only -r ${TRAVIS_COMMIT} | grep -i "sdrf.txt" 1 > changed_files.txt || true