os: linux
language: python

install:
  - pip install click
  - pip install pandas_schema
  - pip install pandas
  - pip install ebi-ols-client
  - pip install sdrfcheck

script:
  - echo `git diff-tree --no-commit-id --name-only -r ${TRAVIS_COMMIT}`
  - echo `git diff-tree --no-commit-id --name-only -r ${TRAVIS_COMMIT}`
  - FILES_CHANGED="$(git diff --name-only $TRAVIS_COMMIT_RANGE)"
  - echo "${FILES_CHANGED}" > files.txt
  - echo "${FILES_CHANGED}"
  - while read -r line; do  if [[ $line == *"sdrf.txt"* ]]; then  echo `python ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/sdrfcheck/sdrfchecker.py validate-sdrf --sdrf_file $line` ; fi; done < files.txt