# This workflow will install Python dependencies and run the included validation script.

name: Validate annotations

on:
  push:
    paths: annotated-projects/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/bigbio/sdrf-pipelines
    - name: Run validation
      run: |
        python validate-all.py -v
